// Package fontkit is the plugin's font shelf: five faces the person can
// pick for a fillable field — three handwriting, two official — each
// embedded as a subset that carries the Latin and Turkish repertoire
// (ı İ ş Ş ğ Ğ ü Ü ö Ö ç Ç and the rest of Latin Extended-A).
//
// The subsets are generated by scripts/fonts.py from google/fonts and
// committed, so a build never needs the network and a signed PDF never
// depends on a font being installed on the reader's machine: the face is
// embedded in the document itself.
//
// A face answers two questions and nothing else: which glyph draws a rune
// (Identity-H writes glyph ids, not characters) and how wide it is. The
// shaping tables are dropped from the subsets because the stamper never
// consults them.
package fontkit

import (
	_ "embed"
	"sort"
	"strings"
	"sync"
	"unicode"

	gtfont "github.com/go-text/typesetting/font"
	"golang.org/x/image/font"
	"golang.org/x/image/font/gofont/goregular"
	"golang.org/x/image/font/sfnt"
	"golang.org/x/image/math/fixed"
)

//go:embed fonts/caveat.ttf
var caveatTTF []byte

//go:embed fonts/dancing-script.ttf
var dancingTTF []byte

//go:embed fonts/homemade-apple.ttf
var homemadeTTF []byte

//go:embed fonts/inter.ttf
var interTTF []byte

//go:embed fonts/source-serif-4.ttf
var serifTTF []byte

// The five ids a manifest, a surface and a stored field all speak.
const (
	Caveat        = "caveat"
	DancingScript = "dancing-script"
	HomemadeApple = "homemade-apple"
	Inter         = "inter"
	SourceSerif   = "source-serif-4"
)

// DefaultID is what an unset or unknown font falls back to.
const DefaultID = Inter

// Face is one embedded font.
type Face struct {
	ID string
	// Family is the human name; PSName goes into the PDF's /BaseFont.
	Family string
	PSName string
	// Script marks the handwriting faces (drawn larger, they sit lower).
	Script bool
	// TTF is the subset embedded into every PDF that uses the face.
	TTF []byte
	// Fetched marks a Noto face downloaded on demand (noto.go): it is
	// subset per document when embedded, since the whole of it is megabytes.
	Fetched bool
	// Shaped marks a face whose text goes through HarfBuzz (layout.go).
	Shaped bool

	gtOnce sync.Once
	gt     *gtfont.Face
	gtErr  error

	once sync.Once
	err  error
	f    *sfnt.Font
	upem float64
	met  font.Metrics
	bbox fixed.Rectangle26_6
}

var faces = []*Face{
	{ID: Caveat, Family: "Caveat", PSName: "Caveat-Regular", Script: true, TTF: caveatTTF},
	{ID: DancingScript, Family: "Dancing Script", PSName: "DancingScript-Regular", Script: true, TTF: dancingTTF},
	{ID: HomemadeApple, Family: "Homemade Apple", PSName: "HomemadeApple-Regular", Script: true, TTF: homemadeTTF},
	{ID: Inter, Family: "Inter", PSName: "Inter-Regular", TTF: interTTF},
	{ID: SourceSerif, Family: "Source Serif 4", PSName: "SourceSerif4-Regular", TTF: serifTTF},
}

var byID = func() map[string]*Face {
	m := make(map[string]*Face, len(faces))
	for _, f := range faces {
		m[f.ID] = f
	}
	return m
}()

// stampFace is the face the rasterised lines under a signature are set in
// (Go Regular, as they always were). It is not offered to anybody: it only
// has to read well at a few pixels, and it has Latin, Greek and Cyrillic.
var stampFace = &Face{ID: "go-regular", Family: "Go", PSName: "GoRegular", TTF: goregular.TTF}

// StampFace is the face of the lines printed under a signature picture.
func StampFace() *Face { return stampFace }

// Segments is a glyph's outline at ppem pixels per em, Y pointing DOWN,
// relative to the pen on the baseline — what a rasteriser draws.
func (f *Face) Segments(gid uint16, ppem float64) (sfnt.Segments, error) {
	if err := f.load(); err != nil {
		return nil, err
	}
	var b sfnt.Buffer
	segs, err := f.f.LoadGlyph(&b, sfnt.GlyphIndex(gid), fixed.Int26_6(ppem*64), nil)
	if err != nil {
		return nil, err
	}
	return append(sfnt.Segments(nil), segs...), nil
}

// All lists the faces in the order the screens offer them.
func All() []*Face { return faces }

// IDs lists the ids, sorted, for validation messages.
func IDs() []string {
	out := make([]string, 0, len(faces))
	for _, f := range faces {
		out = append(out, f.ID)
	}
	sort.Strings(out)
	return out
}

// aliases are the ids the WIRE speaks where they differ from this build's.
//
// ⚠⚠ filex's renderer calls the serif face `source-serif`
// (docs/APP-PLUGINS-API.md → "Faces and rules"); this package has always
// called it `source-serif-4`. Nothing translated between the two, so a box
// the requester set in the serif face arrived as an id this build did not
// know and was stamped in Inter — the choice was offered, taken, and
// silently ignored (found 2026-09-21). Both spellings now mean the same
// face, and WireID answers the renderer in its own.
var aliases = map[string]string{"source-serif": SourceSerif}

// Canonical is this build's id for a face, whichever spelling arrived.
func Canonical(id string) string {
	if a, ok := aliases[id]; ok {
		return a
	}
	return id
}

// WireID is the id filex's renderer knows a face by.
func WireID(id string) string {
	if Canonical(id) == SourceSerif {
		return "source-serif"
	}
	return id
}

// Valid reports whether id names one of the faces.
func Valid(id string) bool { _, ok := byID[Canonical(id)]; return ok }

// Get returns the face, or the default one for an empty or unknown id —
// a stored field with a font this build dropped still stamps.
func Get(id string) *Face {
	if f, ok := byID[Canonical(id)]; ok {
		return f
	}
	return byID[DefaultID]
}

// Default is the face used when nobody chose one.
func Default() *Face { return byID[DefaultID] }

// load parses the subset once per face.
func (f *Face) load() error {
	f.once.Do(func() {
		parsed, err := sfnt.Parse(f.TTF)
		if err != nil {
			f.err = err
			return
		}
		f.f = parsed
		f.upem = float64(parsed.UnitsPerEm())
		var b sfnt.Buffer
		ppem := fixed.Int26_6(parsed.UnitsPerEm()) << 6
		f.met, _ = parsed.Metrics(&b, ppem, font.HintingNone)
		f.bbox, _ = parsed.Bounds(&b, ppem, font.HintingNone)
	})
	return f.err
}

// Glyph is one positioned glyph: the id Identity-H writes, the advance and
// the offsets in 1/1000 em (the unit PDF text space uses; offsets y-up), the
// character it came from, and — for the first glyph of a cluster — the text
// it stands for, which the PDF's ToUnicode map gives back when the stamped
// text is copied. A shaped glyph may stand for several characters (a
// ligature, a conjunct) or share one with others (a base and its mark).
type Glyph struct {
	GID     uint16
	Rune    rune
	Advance float64
	XOffset float64
	YOffset float64
	Text    string
	// Cont marks a glyph that continues a cluster begun by the glyph before
	// it in logical order: it stands for no text of its own.
	Cont bool
}

// Shape maps a string onto glyphs of THIS face alone. A rune the subset
// does not carry is dropped rather than drawn as .notdef — a missing
// character is better than a black box in a contract. Use ShapeRuns to
// have the missing ones borrowed from another face instead.
func (f *Face) Shape(s string) ([]Glyph, error) {
	if err := f.load(); err != nil {
		return nil, err
	}
	out := make([]Glyph, 0, len(s))
	for _, r := range s {
		if g, ok := f.glyph(r); ok {
			out = append(out, g)
		}
	}
	return out, nil
}

// glyph looks one rune up in this face.
func (f *Face) glyph(r rune) (Glyph, bool) {
	if f.load() != nil {
		return Glyph{}, false
	}
	var b sfnt.Buffer
	gid, err := f.f.GlyphIndex(&b, r)
	text := ""
	if r != ' ' && unicode.Is(unicode.Zs, r) {
		// ⚠⚠ A space the face does not carry is drawn with the face's own
		// space. The French audit trail puts a narrow no-break space (U+202F)
		// before “;”, “!” and “?” — French typography, as filex's French
		// pack writes it — and the embedded Inter subset stops at U+2027, so
		// those spaces were DROPPED and the words ran together (2026-09-22,
		// TestAudit_EveryLanguageIsInTheEmbeddedFace). A space has no
		// outline, so nothing is borrowed from another face; only its width
		// is the ordinary one.
		//
		// ⚠ And whenever a space is drawn WITH the space glyph — this
		// fallback, or a face whose own cmap maps U+00A0 there (Source Serif
		// 4 does) — its text is " ": the ToUnicode map keeps one text per
		// glyph for the whole document, so a space glyph that recorded the
		// no-break space first would copy EVERY space out as one.
		space, serr := f.f.GlyphIndex(&b, ' ')
		if err != nil || gid == 0 {
			gid, err = space, serr
		}
		if serr == nil && space != 0 && gid == space {
			text = " "
		}
	}
	if err != nil || gid == 0 {
		return Glyph{}, false
	}
	ppem := fixed.Int26_6(f.f.UnitsPerEm()) << 6
	adv, err := f.f.GlyphAdvance(&b, gid, ppem, font.HintingNone)
	if err != nil {
		return Glyph{}, false
	}
	return Glyph{GID: uint16(gid), Rune: r, Text: text, Advance: float64(adv) / 64 * 1000 / f.upem}, true
}

// AdvanceOf is the face's own advance for a glyph id, per 1000 em — the
// width a PDF records for it.
func (f *Face) AdvanceOf(gid uint16) float64 {
	if f.load() != nil {
		return 0
	}
	var b sfnt.Buffer
	ppem := fixed.Int26_6(f.f.UnitsPerEm()) << 6
	adv, err := f.f.GlyphAdvance(&b, sfnt.GlyphIndex(gid), ppem, font.HintingNone)
	if err != nil {
		return 0
	}
	return float64(adv) / 64 * 1000 / f.upem
}

// Run is a stretch of text drawn with one face. Shaped runs place each
// glyph where the shaper put it (offsets, contextual advances); the others
// are drawn as one string of glyphs.
type Run struct {
	Face   *Face
	Glyphs []Glyph
	Shaped bool
}

// fallbacks are the faces a glyph may be borrowed from when the chosen
// one does not have it. Homemade Apple, for one, has no Ş, ğ or İ: a
// Turkish name in it would otherwise come out with holes in it, so the
// missing letters are taken from the nearest face that has them — a
// handwriting face for a handwriting choice, an official one otherwise.
func fallbacks(primary *Face) []*Face {
	var out []*Face
	add := func(id string) {
		if f := byID[id]; f != nil && f != primary {
			out = append(out, f)
		}
	}
	if primary.Script {
		add(Caveat)
		add(DancingScript)
	}
	add(Inter)
	add(SourceSerif)
	return out
}

// ShapeRuns lays s out (LayoutLine) and returns its runs in visual order.
// What no face can draw is left out; ask Missing (or LayoutLine) to learn
// what that was, and say so — never drop a character silently.
func ShapeRuns(primary *Face, s string) ([]Run, error) {
	line, err := LayoutLine(primary, s)
	if err != nil {
		return nil, err
	}
	return line.Runs, nil
}

// Covers reports whether every character of s can be drawn — by the chosen
// face, a bundled fallback, or a Noto face that could be fetched.
func Covers(primary *Face, s string) bool {
	return len(MissingIn(primary, s)) == 0
}

// MissingIn lists the characters of s that would not be printed, and why.
func MissingIn(primary *Face, s string) []Missing {
	_, missing := Printed(primary, s)
	return missing
}

// Printed is s as the paper will carry it — without the characters no face
// can draw — and what was left out. A screen shows THIS as the preview, so
// what the person approves is what is stamped (the owner, 2026-09-21).
func Printed(primary *Face, s string) (string, []Missing) {
	line, err := LayoutLine(primary, s)
	if err != nil {
		var out []Missing
		for i, r := range []rune(s) {
			out = append(out, Missing{Rune: r, Script: ScriptOf(r), Reason: NoGlyph, At: i})
		}
		return "", out
	}
	if len(line.Missing) == 0 {
		return s, nil
	}
	gone := make(map[int]bool, len(line.Missing))
	for _, m := range line.Missing {
		gone[m.At] = true
	}
	var b strings.Builder
	for i, r := range []rune(s) {
		if !gone[i] {
			b.WriteRune(r)
		}
	}
	return b.String(), line.Missing
}

// RunsWidth is the advance width of runs at size points.
func RunsWidth(runs []Run, size float64) float64 {
	total := 0.0
	for _, run := range runs {
		for _, g := range run.Glyphs {
			total += g.Advance
		}
	}
	return total * size / 1000
}

// Width is the advance width of s at size points, fallbacks included.
func (f *Face) Width(s string, size float64) float64 {
	runs, err := ShapeRuns(f, s)
	if err != nil {
		return 0
	}
	return RunsWidth(runs, size)
}

// Ascent and Descent are per 1000 units of em; Descent is negative.
func (f *Face) Ascent() float64 {
	if f.load() != nil {
		return 750
	}
	return float64(f.met.Ascent) / 64 * 1000 / f.upem
}

func (f *Face) Descent() float64 {
	if f.load() != nil {
		return -250
	}
	return -float64(f.met.Descent) / 64 * 1000 / f.upem
}

// CapHeight per 1000, used by the PDF font descriptor.
func (f *Face) CapHeight() float64 {
	if f.load() != nil {
		return 700
	}
	if f.met.CapHeight > 0 {
		return float64(f.met.CapHeight) / 64 * 1000 / f.upem
	}
	return f.Ascent() * 0.7
}

// BBox is the font bounding box per 1000, as /FontBBox wants it.
func (f *Face) BBox() [4]float64 {
	if f.load() != nil {
		return [4]float64{-200, -250, 1000, 900}
	}
	k := 1000 / f.upem / 64
	return [4]float64{
		float64(f.bbox.Min.X) * k, float64(f.bbox.Min.Y) * k,
		float64(f.bbox.Max.X) * k, float64(f.bbox.Max.Y) * k,
	}
}

// FitSize is the largest size (at most max, never below min) at which s
// fits a box of boxW × boxH points. It is what a field stamp uses when
// nobody pinned a size.
func (f *Face) FitSize(s string, boxW, boxH, min, max float64) float64 {
	if s == "" || boxW <= 0 || boxH <= 0 {
		return min
	}
	// The line's own height caps the size before its width does.
	lineRatio := (f.Ascent() - f.Descent()) / 1000
	if lineRatio <= 0 {
		lineRatio = 1.2
	}
	size := boxH / lineRatio
	if size > max {
		size = max
	}
	// The width is linear in the size, so the line is laid out ONCE: since
	// the width means shaping (HarfBuzz for Arabic or Devanagari), a layout
	// per trial size was a dozen shapings for one box.
	perPoint := f.Width(s, 1)
	for size > min {
		if perPoint*size <= boxW {
			break
		}
		size *= 0.94
	}
	if size < min {
		size = min
	}
	return size
}
