package fontkit

import (
	"errors"
	"strings"
	"sync"
)

// ── Noto, fetched on demand ────────────────────────────────────────────
//
// ⚠⚠ The five bundled faces draw Latin and Turkish, nothing else. A name in
// Japanese, a box filled in Arabic, an audit line in Hindi came out with the
// letters silently missing. The owner (2026-09-21): every script the library
// can draw must print, and the fonts are FETCHED when such text is used —
// "online çekebilirsek 0 MB" — so the module does not grow by the tens of
// megabytes a CJK face weighs, and the common case (Latin, Turkish) never
// touches the network.
//
// noto_table.go (generated by scripts/notogen, never edited by hand) pins
// every face by URL and sha256. The host downloads a face once through its
// guarded outbound path (the app's `http:fonts.gstatic.com` permission, shown
// at install), refuses bytes that do not match the hash, and keeps the file
// in the app's cache: a second use costs no network at all.

// NotoFont is one pinned face: where it is, what its bytes hash to, and how
// many there are (the host refuses a download larger than that).
type NotoFont struct {
	Family string
	URL    string
	SHA256 string
	Size   int64
}

// Fetcher downloads a pinned face (the app wires it to asset_fetch). It
// returns the file's bytes, or why they could not be had.
type Fetcher func(NotoFont) ([]byte, error)

var (
	notoMu    sync.Mutex
	fetcher   Fetcher
	notoFaces = map[string]*Face{} // family → face, for the life of the module instance
	// ⚠ In filex an instance lives for ONE call (measured 2026-09-21: a
	// second use of a cached Japanese face costs ~150 ms of re-reading and
	// parsing it, not a download). The memo still saves the re-parse for
	// every line of that call — a stamp, its preview and its audit trail.
	notoFailed = map[string]error{} // family → why not, for this call only
)

// SetFetcher wires the download. Without one no Noto face is ever
// available, and text that needs one is reported as unprintable. A new
// source starts from nothing: faces had from the previous one are
// forgotten (an app is built once per module, so in filex this happens
// once; a test gets a clean module per app it builds).
func SetFetcher(f Fetcher) {
	notoMu.Lock()
	defer notoMu.Unlock()
	fetcher = f
	notoFaces = map[string]*Face{}
	notoFailed = map[string]error{}
}

// BeginCall forgets the failures of the previous call. A failure is kept
// for the rest of ONE call — an offline instance must not be asked the same
// question for every letter — but never longer: the network may be back.
func BeginCall() {
	notoMu.Lock()
	defer notoMu.Unlock()
	notoFailed = map[string]error{}
}

// ErrNoFetcher is why a face could not be had when nothing can download.
var ErrNoFetcher = errors.New("fontkit: no font source is wired")

// ErrStillDownloading is what a Fetcher wraps when the face is on its way
// but did not arrive within this call: the text is reported as Downloading,
// not Unavailable — "wait a moment", not "check the network".
var ErrStillDownloading = errors.New("fontkit: the font is still downloading")

// unshaped are the Noto faces drawn by their character map alone: very
// large faces for scripts that need no shaping to be right in a line of
// horizontal text (CJK ideographs and kana, Hangul syllables, Tangut,
// Khitan). The shaping engine parses a whole face into memory, which for
// Noto Sans SC is 38 MB beside the file's own 10 — so these are read the
// light way.
var unshaped = map[string]bool{
	"Noto Sans JP": true, "Noto Sans KR": true, "Noto Sans SC": true, "Noto Sans TC": true, "Noto Sans HK": true,
	"Noto Serif Tangut": true, "Noto Serif Khitan Small Script": true,
}

// notoFace returns the face for a family, fetching it the first time.
func notoFace(family string) (*Face, error) {
	notoMu.Lock()
	if f, ok := notoFaces[family]; ok {
		notoMu.Unlock()
		return f, nil
	}
	if err, ok := notoFailed[family]; ok {
		notoMu.Unlock()
		return nil, err
	}
	pin, ok := notoFonts[family]
	fetch := fetcher
	notoMu.Unlock()
	if !ok {
		return nil, errors.New("fontkit: no pinned face for " + family)
	}
	if fetch == nil {
		return nil, ErrNoFetcher
	}
	data, err := fetch(pin)
	if err == nil && int64(len(data)) != pin.Size {
		err = errors.New("fontkit: " + family + " arrived with the wrong size")
	}
	var face *Face
	if err == nil {
		face = &Face{
			ID: "noto:" + family, Family: family,
			PSName: strings.ReplaceAll(family, " ", "") + "-Regular",
			TTF:    data, Fetched: true, Shaped: !unshaped[family],
		}
		err = face.load()
	}
	notoMu.Lock()
	defer notoMu.Unlock()
	if err != nil {
		notoFailed[family] = err
		return nil, err
	}
	notoFaces[family] = face
	return face, nil
}

// ScriptFamilies lists the Noto families that draw a script, in the order
// they are tried; nil when none does.
func ScriptFamilies(script string) []string { return notoScripts[script] }

// Unsupported reports whether no Noto face draws the script at all.
func Unsupported(script string) bool {
	for _, s := range notoNone {
		if s == script {
			return true
		}
	}
	return false
}

// PinnedFonts lists every face the app may fetch (for tests and the docs).
func PinnedFonts() []NotoFont {
	out := make([]NotoFont, 0, len(notoFonts))
	for _, f := range notoFonts {
		out = append(out, f)
	}
	return out
}

// PinnedScripts lists the scripts the table maps (for tests).
func PinnedScripts() map[string][]string { return notoScripts }
